// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxY64_ZUu9Nvbm8x2Stye0rN7opWQ1U8A',
    appId: '1:1033469084474:web:6623a9af18e071a764c603',
    messagingSenderId: '1033469084474',
    projectId: 'purchase_manager-3e47f',
    authDomain: 'purchase_manager-3e47f.firebaseapp.com',
    storageBucket: 'purchase_manager-3e47f.appspot.com',
    measurementId: 'G-LYYSTZSVHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCqO4F_YcVKNaj1oBdmfKzmWOM5pRBfLE',
    appId: '1:1033469084474:android:0fcccb6d1b3f424d64c603',
    messagingSenderId: '1033469084474',
    projectId: 'purchase_manager-3e47f',
    storageBucket: 'purchase_manager-3e47f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbKwHwWdgmwM3-Z150rWdalbc4XhvcjZI',
    appId: '1:1033469084474:ios:54aeb22bcc31f04b64c603',
    messagingSenderId: '1033469084474',
    projectId: 'purchase_manager-3e47f',
    storageBucket: 'purchase_manager-3e47f.appspot.com',
    iosClientId:
        '1033469084474-op6lteciqhq0r5lsdsjspdpg2idjnal9.apps.googleusercontent.com',
    iosBundleId: 'com.example.purchase_manager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbKwHwWdgmwM3-Z150rWdalbc4XhvcjZI',
    appId: '1:1033469084474:ios:59e1c2970516683864c603',
    messagingSenderId: '1033469084474',
    projectId: 'purchase_manager-3e47f',
    storageBucket: 'purchase_manager-3e47f.appspot.com',
    iosClientId:
        '1033469084474-bq7rvtvam750grsu3mkt9fkr8rvua2au.apps.googleusercontent.com',
    iosBundleId: 'com.example.purchase_manager.RunnerTests',
  );
}
